### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/shared-userspace#1]
s-u includes SDL, which in turn includes SDL-devel. The -devel package needs mesa-libGLU-devel which is being filtered out from the module. So maybe SDL-devel should be filtered out too?

**Comment by r4f4** [comment]
package: freeglut-devel-3.0.0-4.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libGLU-devel

**Comment by r4f4** [comment]
package: mesa-libEGL-17.1.2-2.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libwayland-client.so.0()(64bit)
     libwayland-server.so.0()(64bit)
package: mesa-libEGL-devel-17.1.2-2.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     pkgconfig(xxf86vm)
package: mesa-libGL-devel-17.1.2-2.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     pkgconfig(xxf86vm)
package: mesa-libgbm-17.1.2-2.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libwayland-client.so.0()(64bit)
     libwayland-server.so.0()(64bit)

**Comment by r4f4** [comment]
package: pango-devel-1.40.6-1.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     pkgconfig(harfbuzz)

**Comment by r4f4** [comment]
package: pprof-2.5.93-1.module_074add9c.noarch from repoclosure-Server.x86_64
  unresolved deps: 
     graphviz
     gv

pprof comes it with gperftools.

**Comment by r4f4** [comment]
package: pulseaudio-10.0-4.module_98c1823a.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libXtst.so.6()(64bit)
     liborc-0.4.so.0()(64bit)
     libsndfile.so.1()(64bit)
     libsndfile.so.1(libsndfile.so.1.0)(64bit)
     libsoxr.so.0()(64bit)
     libspeexdsp.so.1()(64bit)
     libwebrtc_audio_processing.so.1()(64bit)
     rtkit
package: pulseaudio-libs-10.0-4.module_98c1823a.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libXtst.so.6()(64bit)
     libasyncns.so.0()(64bit)
     libsndfile.so.1()(64bit)
     libsndfile.so.1(libsndfile.so.1.0)(64bit)

**Comment by r4f4** [comment]
package: vala-0.36.3-1.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     gobject-introspection-devel

**Comment by asamalik** [comment]
Why do we need SDL?

I found out all the modules requiring shared-userspace in runtime, and listed all their `default` install profile packages. I have then generated a [dependency graph](https://asamalik.fedorapeople.org/boltron-runtime-deps.svg) using my [modularity-dep-viz](https://github.com/asamalik/modularity-dep-viz) tool. The tool doesn't work 100 % correctly, but it gives at least something.

And guess what! I couldn't find anything requiring SCL. Can we dump it?

Modules requiring shared-userspace in runtime and their default install profile packages:

```
container-runtime          
- docker
dhcp        
- dhcp-client
- dhcp-common
- dhcp-libs
- ipcalc
- iproute
- iputils                            
dnf                      
- dnf
mariadb
 - mariadb
 - mariadb-server
 - gettext
memcached                  
 - memcached
mongodb
 - mongodb
 - mongodb-server
 - gettext         
nodejs
 - nodejs
 - npm                  
php
 - php                     
source-to-image       
- source-to-image     
sssd   
 - sssd
 - sssd-ad
 - sssd-common
 - sssd-common-pac
 - sssd-dbus
 - sssd-ipa
 - sssd-krb5
 - sssd-krb5-common
 - sssd-ldap
 - sssd-libwbclient
 - sssd-nfs-idmap
 - sssd-proxy
 - sssd-tools
 - sssd-winbind-idmap
varnish
 - varnish
```

**Comment by KarstenHopp** [comment]
See card 1044 in our trello where a bunch of tier1 packages including SDL have been requested to be in s-u. But as we're dropping s-u in favor of platform anyway, I have no objection to remove it here.

**Comment by r4f4** [comment]
package: policycoreutils-python3-2.6-5.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     audit-libs-python3 >= 0:2.1.3-4

**Comment by r4f4** [comment]
package: systemtap-devel-3.1-5.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     kernel-devel-uname-r
package: systemtap-runtime-3.1-5.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libdyninstAPI.so.9.3()(64bit)
     libsymtabAPI.so.9.3()(64bit)
package: systemtap-runtime-virthost-3.1-5.module_f9511cd3.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     libvirt >= 0:1.0.2
     libvirt.so.0()(64bit)
     libvirt.so.0(LIBVIRT_0.0.3)(64bit)
     libvirt.so.0(LIBVIRT_0.1.0)(64bit)
     libvirt.so.0(LIBVIRT_0.1.1)(64bit)
     libvirt.so.0(LIBVIRT_0.1.5)(64bit)
     libvirt.so.0(LIBVIRT_0.1.9)(64bit)
     libvirt.so.0(LIBVIRT_0.3.0)(64bit)
     libvirt.so.0(LIBVIRT_0.4.0)(64bit)
     libvirt.so.0(LIBVIRT_0.7.2)(64bit)
     libvirt.so.0(LIBVIRT_0.7.3)(64bit)
     libvirt.so.0(LIBVIRT_0.9.0)(64bit)
     libvirt.so.0(LIBVIRT_0.9.13)(64bit)
     libvirt.so.0(LIBVIRT_0.9.2)(64bit)
     libvirt.so.0(LIBVIRT_0.9.3)(64bit)
     libvirt.so.0(LIBVIRT_1.0.2)(64bit)

**Comment by nphilipp** [comment]
Seems we've caught everything affecting shared-userspace meanwhile:

https://kojipkgs.fedoraproject.org/compose/Fedora-Modular-26-20170707.n.0/logs/x86_64/repoclosure-Server.x86_64.log
