### ISSUE TITLE
git can't be installed

### ISSUE THREAD

**Issue by TomasTomecek** [modularity-modules/shared-userspace#2]
```
DEBUG:  Problem 1: conflicting requests
DEBUG:   - nothing provides perl(strict) needed by git-2.13.0-2.module_1769159c.x86_64
```

not sure if the package is present in one of the perl's modules.

**Comment by ignatenkobrain** [comment]
@TomasTomecek `nothing provides` means that nothing provides that thing ;)

This is part of perl-libs actually, so probably someone forgot to add dependency or filtered it out

**Comment by TomasTomecek** [comment]
> `nothing provides` means that nothing provides that thing ;)

if you omit runtime require on the specific module, it won't be picked, that's what I meant

**Comment by nphilipp** [comment]
We changed a lot of dependency-related issues in the meantime, and with the [current Boltron images](https://kojipkgs.fedoraproject.org/compose/26/latest-Fedora-Modular-26/compose/Server/x86_64/images/), I could install `git` using either `microdnf` or `dnf` (after installing the latter).
